// packages/vue/src/Animate.vue
<template>
  <transition>
    <div :style="calcStyle()">
      <slot>
      </slot>
    </div>
  </transition>
</template>

<script>
// @flow

import Vue from 'vue';
import { orchestrator, removeFromStore, addListener } from 'yubaba-core';

export default {
  name: 'yubaba-animate',

  props: {
    pair: String,
    animations: Array,
  },

  data() {
    return {
      visible: false,
    };
  },

  mounted () {
    this._detatch = addListener(this.pair, this.setVisibility);
    this.initialise();
  },

  beforeDestroy () {
    this._detatch();
    this.initialise();

    console.log(this.$el.getBoundingClientRect());
    console.log(this._isBeingDestroyed);

    if (this.$el.firstElementChild) {
      removeFromStore(this.pair, this.$el.firstElementChild, true);
    }
  },

  methods: {
    calcStyle () {
      return {
        opacity: this.visible ? 1 : 0,
      };
    },
    initialise () {
      if (!this.$el.firstElementChild) {
        return;
      }

      orchestrator(this.pair, {
        node: this.$el.firstElementChild,
        animations: this.animations,
        shouldShow: this.setVisibility,
      });
    },
    setVisibility(visible) {
      this.visible = visible;
    },
  },
};
</script>

// packages/react/src/Animate.js
// @flow

import type { Children } from 'react';
import type { Animation } from 'yubaba-core';

import React from 'react';
import { orchestrator, removeFromStore, addListener } from 'yubaba-core';

export default class Animate extends React.Component {
  _node: HTMLElement;
  _detatch: Function;

  props: {
    pair: string,
    children?: Children,
    animations: Array<Animation>,
    style?: {
      [string]: any,
    },
  };

  state = {
    visible: false,
  };

  componentDidMount () {
    this._detatch = addListener(this.props.pair, this.setVisibility);
    this.initialise();
  }

  componentWillUnmount () {
    this._detatch();
    this.initialise();

    if (this._node.firstElementChild) {
      removeFromStore(this.props.pair, this._node.firstElementChild, true);
    }
  }

  setVisibility = (visible: boolean) => {
    this.setState({
      visible,
    });
  };

  initialise () {
    if (!this._node.firstElementChild) {
      return;
    }

    orchestrator(this.props.pair, {
      node: this._node.firstElementChild,
      animations: this.props.animations,
      shouldShow: this.setVisibility,
    });
  }

  render () {
    const { pair, animations, style, ...props } = this.props;

    return (
      <div
        {...props}
        ref={(node) => (this._node = node)}
        style={{ ...style, opacity: this.state.visible ? 1 : 0 }}
      >
        {this.props.children}
      </div>
    );
  }
}
